# Generated by Django 3.1.7 on 2021-04-08 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20210407_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
