# Generated by Django 3.1.7 on 2021-04-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_todolist_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
