# Generated by Django 3.1.7 on 2021-04-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todolist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='model_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(default='uncompleted', max_length=11),
        ),
    ]
