# Generated by Django 3.1.7 on 2021-04-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20210408_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UncompletedTask',
            new_name='ToDoList',
        ),
    ]
