# Generated by Django 3.1.7 on 2021-04-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_auto_20210408_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='model_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], default='1', max_length=6),
        ),
    ]
