# Generated by Django 3.1.7 on 2021-04-08 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20210408_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('priority', models.CharField(max_length=6)),
                ('complete_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='NotCompletedTasks',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('priority', models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], default='1', max_length=6)),
                ('create_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
