# Generated by Django 3.1.7 on 2021-04-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_auto_20210412_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notcompletedtasks',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=1, max_length=1),
        ),
    ]
